service:
  KKP:
    service_id: "KKP"
    service_name: "KKP"
    product_code: "KKP"
    username: "Hkleader"
    password: "$e4R^3CKj01Kx*@o"
    operator: "1"
    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    mrchant_id: "247"
    prod_price: "2"
    img_path: "http://eg.c4fungames.com/static/img/bg.png"
    operator_id: "1"
    sub_package: "D"
    content_url: "http://eg.c4fungames.com?subID={subID}"
    register_url: "http://eg.c4fungames.com/addsubs?sign=mondia&user={subID}"
    LP_url: "http://eg.c4fungames.com/mm/eg/lp?affName=ERROR"
    mondia_request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    get_customer_callback_url: "http://mm-eg.leadernethk.com/get/customer/"
    unsub_get_customer_callback_url: "http://mm-eg.leadernethk.com/unsub/get/customer/KKP"
    sub_result_redirect: "http://mm-eg.leadernethk.com/get/sub_result/"
    unsub_pin_message: "رقم التعريف الشخصي هو {PIN}"
    language: "eg"
    success_sub_message: "تهانينا على اشتراكك الناجح في خدمة C4FunGame ، يرجى زيارة http://eg.c4fungames.com ، فإن حسابك هو {subID}"
  KKP_IQ:
    service_id: "KKP_IQ"
    service_name: "KKP_IQ"
    product_code: "KKP"
    username: "Hkleader"
    password: "$e4R^3CKj01Kx*@o"
    operator: "27"
    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    mrchant_id: "247"
    prod_price: "200"
    img_path: "http://iq.argameloft.com/static/img/bg.png"
    operator_id: "27"
    sub_package: "D"
    content_url: "http://iq.argameloft.com?subID={subID}"
    register_url: "http://iq.argameloft.com/addsubs?sign=mondia&user={subID}"
    LP_url: "http://iq.argameloft.com/mm/iq/lp?affName=ERROR"
    mondia_request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    get_customer_callback_url: "http://mm-eg.leadernethk.com/get/customer/"
    unsub_get_customer_callback_url: "http://mm-eg.leadernethk.com/unsub/get/customer/KKP"
    sub_result_redirect: "http://mm-eg.leadernethk.com/get/sub_result/"
    unsub_pin_message: "رقم التعريف الشخصي هو {PIN}"
    language: "iq"
    success_sub_message: "تهانينا على اشتراكك الناجح في خدمة C4FunGame ، يرجى زيارة http://iq.argameloft.com ، فإن حسابك هو {subID}"
#service:
#  KKP:
#    service_id: "KKP"
#    service_name: "KKP"
#    product_code: "KKP"
#    username: "Hkleader"
#    password: "$e4R^3CKj01Kx*@o"
#    operator: "1"
#    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
#    mrchant_id: "293"
#    prod_price: "2"
#    img_path: "http://eg.c4fungames.com/static/img/bg.png"
#    operator_id: "1"
#    sub_package: "D"
#    content_url: "http://eg.c4fungames.com?subID={subID}"
#    register_url: "http://eg.c4fungames.com/addsubs?sign=mondia&user={subID}"
#    LP_url: "http://eg.c4fungames.com/mm/eg/lp?affName=ERROR"
#    mondia_request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
#    get_customer_callback_url: "http://mm-eg.leadernethk.com/get/customer/"
#    sub_result_redirect: "http://mm-eg.leadernethk.com/get/sub_result/"
#    unsub_pin_message: "رقم التعريف الشخصي هو {PIN}"
#    language: "eg"
#    success_sub_message: "تهانينا على اشتراكك الناجح في خدمة C4FunGame ، يرجى زيارة http://eg.c4fungames.com ، فإن حسابك هو {subID}"
