service:
  REDLIGHTVIDEOS:
    service_id: "REDLIGHTVIDEOS"
    service_name: "REDLIGHTVIDEOS"
    product_code: "REDLIGHTVIDEOS"
    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    mrchant_id: "93"
    prod_price: "9.9"
    img_path: "http://www.redlightvideos.com/lp/tn/uk/img/banner.jpg"
    operator_id: "8"
    sub_package: "W"
    content_url: "http://www.redlightvideos.com"
    register_url: "http://www.redlightvideos.com/addsubs?sign=mondia&user={subID}"
    LP_url: "http://www.redlightvideos.com/lp/mm/pl/index.html?affName=ERROR"
  GOGAMEHUB:
    service_id: "GOGAMEHUB"
    service_name: "GOGAMEHUB"
    product_code: "GOGAMEHUB"
    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    mrchant_id: "93"
    prod_price: "9.9"
    img_path: "http://www.gogamehub.com/static/img/gogame_banner.jpg"
    operator_id: "8"
    sub_package: "W"
    content_url: "http://www.gogamehub.com/mm/pl?subId={subID}"
    register_url: "http://www.gogamehub.com/addusername?username={subID}&sign=mondia_pl&subId={subID}"
    LP_url: "http://www.gogamehub.com/lp/mm/pl?affName=ERROR"
  IFUNNY:
    service_id: "IFUNNY"
    service_name: "IFUNNY"
    product_code: "IFUNNY"
    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    mrchant_id: "93"
    prod_price: "9.9"
    img_path: "http://pl.ifunnyhub.com/static/img/banner.png"
    operator_id: "8"
    sub_package: "W"
    content_url: "http://pl.ifunnyhub.com?subID={subID}"
    register_url: "http://pl.ifunnyhub.com?user={subID}&pass=123456&sign=mondia_pl"
    LP_url: "http://pl.ifunnyhub.com/mm/pl/lp?affName=ERROR"
  PREPRON4K:
    service_id: "PREPRON4K"
    service_name: "PREPRON4K"
    product_code: "PREPRON4K"
    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    mrchant_id: "93"
    prod_price: "9.9"
    img_path: "http://pl.4kpreporn.com/static/img/banner.png"
    operator_id: "8"
    sub_package: "W"
    content_url: "http://pl.4kpreporn.com?subID={subID}"
    register_url: "http://pl.4kpreporn.com?user={subID}&pass=123456&sign=mondia_pl"
    LP_url: "http://pl.4kpreporn.com/mm/pl/lp?affName=ERROR"
  PLEASURECLICK:
    service_id: "PLEASURECLICK"
    service_name: "PLEASURECLICK"
    product_code: "PLEASURECLICK"
    request_url: "http://login.mondiamediamena.com/billinggw-lcm/billing"
    mrchant_id: "93"
    prod_price: "9.9"
    img_path: "http://pl.pleasureclip.com/static/img/banner.png"
    operator_id: "8"
    sub_package: "W"
    content_url: "http://pl.pleasureclip.com?subID={subID}"
    register_url: "http://pl.pleasureclip.com/adduser?user={subID}&pass=123456&sign=mondia_pl"
    LP_url: "http://pl.pleasureclip.com/mm/pl/lp?affName=ERROR"
#service:
#  PinkCity4K:
#    service_id: "PRD_LEADERHK_PT_PINKCITY_GENERIC"
#    service_name: "TEST_LEADER"
#    username: "leadertestapi"
#    password: "HK&ld&88"
#    content_url: "http://content.com"
#    unsub_url: "http://unsub"
#    register_url: "http://register.com"
#    delete_url:  "http://delete"
#    LP_url: "http://LP"
#    price: "2.99"
#    currency: "GBP"
#    wap_v2_url: "https://test.go4mobility.com/api/wapBillingV2?WSDL"
#
#
